import { Request, Response } from 'express';
import bcrypt from 'bcryptjs';
import { Course } from '../models/Course';
import { User } from '../models/User';

const initialCourses = [
  {
    id: 'course-programming-101',
    title: 'Programming Fundamentals',
    slug: 'programming-fundamentals',
    description: 'Master core computational thinking, variables, control flow logic, loops, and function abstractions.',
    iconName: 'Code',
    category: 'Programming',
    level: 'Beginner',
    estimatedHours: '3 Hours',
    passingScorePercent: 70,
    lessons: [
      {
        id: 'prog-les-1',
        courseId: 'course-programming-101',
        title: 'Introduction to Algorithms & Variables',
        order: 1,
        summary: 'Understand memory storage, data types, and step-by-step program execution.',
        explanation: 'A computer program is a step-by-step sequence of instructions given to a computer. A variable is a named storage container in memory used to hold data values such as numbers, text strings, and booleans.',
        keyPoints: [
          'Variables store data in computer memory (RAM).',
          'Data types specify the kind of value (e.g., Integer, String, Boolean).',
          'Code executes line-by-line in sequential order.',
        ],
        exampleCode: `let studentName = "Sarah";\nlet totalScore = 95;\nlet isPassed = true;\n\nconsole.log(studentName + " scored " + totalScore);`,
        practiceQuestion: {
          question: 'Which statement correctly creates a variable storing a number in JavaScript?',
          options: ['let count = 10;', 'variable count = "10";', 'count := integer(10)', 'create number count = 10;'],
          correctAnswer: 0,
          explanation: 'In JavaScript/TypeScript, `let count = 10;` declares a variable with an integer value.',
        },
        xpReward: 20,
      },
      {
        id: 'prog-les-2',
        courseId: 'course-programming-101',
        title: 'Conditional Logic & Decision Making',
        order: 2,
        summary: 'Control program flow using IF, ELSE IF, and ELSE branching conditions.',
        explanation: 'Conditionals allow programs to execute different code blocks depending on whether a logical statement evaluates to true or false.',
        keyPoints: [
          '`if` statements check whether a logical condition is true.',
          '`else if` allows testing multiple sequential conditions.',
          '`else` acts as the fallback execution path.',
        ],
        exampleCode: `let score = 85;\n\nif (score >= 70) {\n  console.log("Course Passed! Certificate Earned.");\n} else {\n  console.log("Keep practicing and try again.");\n}`,
        practiceQuestion: {
          question: 'What will be printed if `score = 65` in `if (score >= 70)`?',
          options: ['Course Passed!', 'Keep practicing and try again.', 'Syntax Error', 'Nothing'],
          correctAnswer: 1,
          explanation: 'Since 65 is less than 70, the condition evaluates to false, executing the `else` block.',
        },
        xpReward: 20,
      },
      {
        id: 'prog-les-3',
        courseId: 'course-programming-101',
        title: 'Loops & Iteration',
        order: 3,
        summary: 'Automate repetitive tasks efficiently using FOR loops and WHILE loops.',
        explanation: 'Loops repeat a block of code multiple times until a specified termination condition is reached, avoiding repetitive code duplication.',
        keyPoints: [
          '`for` loops run a fixed number of known iterations.',
          '`while` loops repeat as long as a boolean condition remains true.',
          'Always ensure loop termination to avoid infinite loops.',
        ],
        exampleCode: `for (let i = 1; i <= 5; i++) {\n  console.log("Completed lesson " + i);\n}`,
        practiceQuestion: {
          question: 'How many times will a loop `for (let i=0; i<3; i++)` run?',
          options: ['2 times', '3 times (i=0, 1, 2)', '4 times', '0 times'],
          correctAnswer: 1,
          explanation: 'The loop executes for i=0, i=1, and i=2, totaling 3 iterations.',
        },
        xpReward: 20,
      },
      {
        id: 'prog-les-4',
        courseId: 'course-programming-101',
        title: 'Functions & Reusable Modular Code',
        order: 4,
        summary: 'Package logic into functions with parameters and return values.',
        explanation: 'Functions are reusable blocks of code designed to perform a specific task. They accept input parameters and return an output result.',
        keyPoints: [
          'Functions promote Code Reusability and DRY principles.',
          'Parameters pass dynamic data into the function body.',
          'The `return` statement sends a result back to the caller.',
        ],
        exampleCode: `function calculateAverage(score1, score2) {\n  return (score1 + score2) / 2;\n}\n\nlet finalGrade = calculateAverage(90, 80); // 85`,
        practiceQuestion: {
          question: 'What keyword sends the result of a function back to the caller?',
          options: ['output', 'send', 'return', 'export'],
          correctAnswer: 2,
          explanation: 'The `return` keyword outputs the calculated value from a function call.',
        },
        xpReward: 20,
      },
    ],
    questions: [
      {
        id: 'prog-q1',
        type: 'multiple_choice',
        questionText: 'What is the primary purpose of a variable in computer programming?',
        options: [
          'To connect the computer to the internet',
          'To store and reference data in memory',
          'To style the web page background color',
          'To compile Python into hardware assembly',
        ],
        correctAnswer: 1,
        explanation: 'Variables are named containers used to store data in memory during program execution.',
      },
      {
        id: 'prog-q2',
        type: 'true_false',
        questionText: 'True or False: A `while` loop will repeat indefinitely if its condition never becomes false.',
        options: ['True', 'False'],
        correctAnswer: 0,
        explanation: 'True. An endless `while` loop is known as an infinite loop.',
      },
      {
        id: 'prog-q3',
        type: 'multiple_choice',
        questionText: 'Which operator checks for equality between two values in JavaScript?',
        options: ['=', '==', '===', '=>'],
        correctAnswer: 2,
        explanation: 'The `===` operator checks strict equality of both value and data type.',
      },
      {
        id: 'prog-q4',
        type: 'true_false',
        questionText: 'True or False: Functions can accept parameters and return computed output values.',
        options: ['True', 'False'],
        correctAnswer: 0,
        explanation: 'True. Functions take input parameters and return output results.',
      },
      {
        id: 'prog-q5',
        type: 'multiple_choice',
        questionText: 'What is the output of `console.log(10 % 3)` (modulo operator)?',
        options: ['3', '3.33', '1', '0'],
        correctAnswer: 2,
        explanation: 'The modulo operator `%` yields the integer remainder of division (10 ÷ 3 = 3 remainder 1).',
      },
    ],
  },
  {
    id: 'course-english-101',
    title: 'English Beginner',
    slug: 'english-beginner',
    description: 'Build confidence in essential English grammar, everyday vocabulary, greetings, and sentence construction.',
    iconName: 'BookOpen',
    category: 'Languages',
    level: 'Beginner',
    estimatedHours: '2.5 Hours',
    passingScorePercent: 70,
    lessons: [
      {
        id: 'eng-les-1',
        courseId: 'course-english-101',
        title: 'Greetings & Self-Introductions',
        order: 1,
        summary: 'Learn polite formal and informal greetings and how to introduce yourself.',
        explanation: 'In English, greetings vary depending on formality. Common formal greetings include "Good morning" and "Pleased to meet you", while informal greetings include "Hello" or "Hi".',
        keyPoints: [
          'Use "Good morning / afternoon / evening" for formal settings.',
          'Introduce yourself with "My name is..." or "I am..."',
          'Respond with "Nice to meet you!"',
        ],
        exampleCode: `Person A: "Hello, my name is Alex. Nice to meet you!"\nPerson B: "Nice to meet you too, Alex! I am Sarah."`,
        practiceQuestion: {
          question: 'Which sentence is correct for introducing yourself?',
          options: ['I name is Sarah.', 'My name is Sarah.', 'Me named Sarah.', 'Mine name Sarah.'],
          correctAnswer: 1,
          explanation: '"My name is Sarah" is the standard grammatically correct introduction.',
        },
        xpReward: 20,
      },
      {
        id: 'eng-les-2',
        courseId: 'course-english-101',
        title: 'Present Simple Tense Basics',
        order: 2,
        summary: 'Express daily habits, general facts, and routines accurately.',
        explanation: 'The Present Simple tense is used to talk about repeated actions, habits, or permanent truths.',
        keyPoints: [
          'Base verb used for I / You / We / They (e.g., "I work every day").',
          'Add -s or -es for He / She / It (e.g., "She works hard").',
          'Negative form uses "do not" or "does not".',
        ],
        exampleCode: `Positive: "He reads a book every evening."\nNegative: "She does not drink coffee."`,
        practiceQuestion: {
          question: 'Choose the correct form: "She ___ to school every morning."',
          options: ['walk', 'walks', 'walking', 'walked'],
          correctAnswer: 1,
          explanation: 'Third-person singular (She) takes the "-s" ending in the Present Simple tense ("walks").',
        },
        xpReward: 20,
      },
      {
        id: 'eng-les-3',
        courseId: 'course-english-101',
        title: 'Essential Vocabulary & Nouns',
        order: 3,
        summary: 'Master common nouns, singular vs plural rules, and articles (a/an/the).',
        explanation: 'Nouns represent people, places, things, or ideas. Use "a" before consonant sounds and "an" before vowel sounds (a, e, i, o, u).',
        keyPoints: [
          'Use "a" for consonant sounds: "a student", "a book".',
          'Use "an" for vowel sounds: "an apple", "an email".',
          'Use "the" when referring to a specific item known to both speakers.',
        ],
        practiceQuestion: {
          question: 'Which phrase uses the correct indefinite article?',
          options: ['a apple', 'an apple', 'an book', 'a email'],
          correctAnswer: 1,
          explanation: '"Apple" begins with a vowel sound, so "an apple" is correct.',
        },
        xpReward: 20,
      },
    ],
    questions: [
      {
        id: 'eng-q1',
        type: 'multiple_choice',
        questionText: 'Choose the correct greeting for 9:00 AM:',
        options: ['Good evening', 'Good night', 'Good morning', 'Good afternoon'],
        correctAnswer: 2,
        explanation: '"Good morning" is used from sunrise until 12:00 PM.',
      },
      {
        id: 'eng-q2',
        type: 'true_false',
        questionText: 'True or False: We use "an" before words starting with a consonant sound like "car".',
        options: ['True', 'False'],
        correctAnswer: 1,
        explanation: 'False. We use "a car", not "an car".',
      },
      {
        id: 'eng-q3',
        type: 'multiple_choice',
        questionText: 'Select the correct sentence:',
        options: [
          'They plays football on weekends.',
          'They play football on weekends.',
          'They play football on weekends.',
          'They playing football on weekends.',
        ],
        correctAnswer: 1,
        explanation: '"They" takes the base verb form "play" in the Present Simple tense.',
      },
      {
        id: 'eng-q4',
        type: 'true_false',
        questionText: 'True or False: "She does not like tea" is a grammatically correct negative sentence.',
        options: ['True', 'False'],
        correctAnswer: 0,
        explanation: 'True. "She does not + base verb" is correct.',
      },
      {
        id: 'eng-q5',
        type: 'multiple_choice',
        questionText: 'What is the plural form of the word "city"?',
        options: ['citys', 'cities', 'cityes', 'citi'],
        correctAnswer: 1,
        explanation: 'Nouns ending in consonant + y change "y" to "ies" (cities).',
      },
    ],
  },
  {
    id: 'course-math-101',
    title: 'Mathematics Fundamentals',
    slug: 'math-fundamentals',
    description: 'Strengthen core algebraic reasoning, linear equations, percentages, and geometric principles.',
    iconName: 'Calculator',
    category: 'Mathematics',
    level: 'Beginner',
    estimatedHours: '3.5 Hours',
    passingScorePercent: 70,
    lessons: [
      {
        id: 'math-les-1',
        courseId: 'course-math-101',
        title: 'Order of Operations (PEMDAS)',
        order: 1,
        summary: 'Solve multi-step numerical expressions using Parentheses, Exponents, Multiplication, Division, Addition, Subtraction.',
        explanation: 'The order of operations guarantees consistent mathematical results across calculations.',
        keyPoints: [
          'P: Parentheses first.',
          'E: Exponents next.',
          'MD: Multiplication and Division (left to right).',
          'AS: Addition and Subtraction (left to right).',
        ],
        exampleCode: `Expression: 5 + 3 * (4 - 2)\nStep 1: (4 - 2) = 2\nStep 2: 3 * 2 = 6\nStep 3: 5 + 6 = 11`,
        practiceQuestion: {
          question: 'What is the value of 10 + 2 * 5?',
          options: ['60', '20', '15', '25'],
          correctAnswer: 1,
          explanation: 'Perform multiplication first: 2 * 5 = 10, then add 10: 10 + 10 = 20.',
        },
        xpReward: 20,
      },
      {
        id: 'math-les-2',
        courseId: 'course-math-101',
        title: 'Solving Linear Equations',
        order: 2,
        summary: 'Isolate unknown variables step-by-step using inverse operations.',
        explanation: 'An equation is a mathematical statement showing that two expressions are equal. To solve for x, apply the same inverse operations to both sides of the equation.',
        keyPoints: [
          'Add/Subtract terms to group variables on one side.',
          'Multiply/Divide to solve for the coefficient of 1.',
          'Check your answer by substituting back into original equation.',
        ],
        exampleCode: `Equation: 2x + 4 = 12\nStep 1: Subtract 4 -> 2x = 8\nStep 2: Divide by 2 -> x = 4`,
        practiceQuestion: {
          question: 'If 3x - 5 = 10, what is the value of x?',
          options: ['x = 3', 'x = 5', 'x = 15', 'x = 4'],
          correctAnswer: 1,
          explanation: '3x = 15 -> x = 5.',
        },
        xpReward: 20,
      },
    ],
    questions: [
      {
        id: 'math-q1',
        type: 'multiple_choice',
        questionText: 'Evaluate: (6 + 4) ÷ 2 * 3',
        options: ['2.5', '15', '1', '12'],
        correctAnswer: 1,
        explanation: '(6+4)=10. Then 10 ÷ 2 = 5. Finally 5 * 3 = 15.',
      },
      {
        id: 'math-q2',
        type: 'true_false',
        questionText: 'True or False: In algebra, 2x means "2 plus x".',
        options: ['True', 'False'],
        correctAnswer: 1,
        explanation: 'False. 2x represents 2 multiplied by x.',
      },
      {
        id: 'math-q3',
        type: 'multiple_choice',
        questionText: 'Solve for y: 4y = 24',
        options: ['y = 6', 'y = 20', 'y = 28', 'y = 96'],
        correctAnswer: 0,
        explanation: 'Divide both sides by 4: y = 24 / 4 = 6.',
      },
      {
        id: 'math-q4',
        type: 'true_false',
        questionText: 'True or False: The area of a rectangle is calculated by multiplying length times width.',
        options: ['True', 'False'],
        correctAnswer: 0,
        explanation: 'True. Area = Length × Width.',
      },
      {
        id: 'math-q5',
        type: 'multiple_choice',
        questionText: 'What is 20% of 150?',
        options: ['15', '20', '30', '45'],
        correctAnswer: 2,
        explanation: '0.20 * 150 = 30.',
      },
    ],
  },
  {
    id: 'course-db-101',
    title: 'Database Fundamentals',
    slug: 'database-fundamentals',
    description: 'Learn relational database design, SQL queries (SELECT, INSERT, UPDATE), tables, primary keys, and data integrity.',
    iconName: 'Database',
    category: 'Databases',
    level: 'Beginner',
    estimatedHours: '3 Hours',
    passingScorePercent: 70,
    lessons: [
      {
        id: 'db-les-1',
        courseId: 'course-db-101',
        title: 'Introduction to Relational Databases & SQL',
        order: 1,
        summary: 'Understand tables, rows, columns, primary keys, and SQL structured query language.',
        explanation: 'A Relational Database Management System (RDBMS) organizes data into structured tables composed of rows (records) and columns (attributes).',
        keyPoints: [
          'Tables store structured records.',
          'Primary Keys uniquely identify each row in a table.',
          'SQL (Structured Query Language) is used to query and mutate data.',
        ],
        exampleCode: `SELECT student_name, score \nFROM students \nWHERE score >= 70;`,
        practiceQuestion: {
          question: 'Which SQL keyword is used to retrieve data from a database table?',
          options: ['GET', 'FETCH', 'SELECT', 'EXTRACT'],
          correctAnswer: 2,
          explanation: 'The `SELECT` statement queries and retrieves records from SQL tables.',
        },
        xpReward: 20,
      },
      {
        id: 'db-les-2',
        courseId: 'course-db-101',
        title: 'Filtering & Sorting Query Results',
        order: 2,
        summary: 'Use WHERE clauses, AND/OR logic, and ORDER BY sorting commands.',
        explanation: 'Filter specific dataset subsets using WHERE conditions and order output records using ORDER BY.',
        keyPoints: [
          '`WHERE` filters rows based on logical conditions.',
          '`ORDER BY column_name ASC|DESC` sorts output records.',
        ],
        exampleCode: `SELECT * FROM courses \nWHERE category = 'Programming' \nORDER BY title ASC;`,
        practiceQuestion: {
          question: 'Which SQL clause filters records based on a specific condition?',
          options: ['GROUP BY', 'WHERE', 'ORDER BY', 'FILTER'],
          correctAnswer: 1,
          explanation: 'The `WHERE` clause filters dataset records.',
        },
        xpReward: 20,
      },
    ],
    questions: [
      {
        id: 'db-q1',
        type: 'multiple_choice',
        questionText: 'What uniquely identifies a row in a relational database table?',
        options: ['Foreign Key', 'Primary Key', 'Index Label', 'Super Key'],
        correctAnswer: 1,
        explanation: 'A Primary Key uniquely identifies every record in a table.',
      },
      {
        id: 'db-q2',
        type: 'true_false',
        questionText: 'True or False: SQL stands for Structured Query Language.',
        options: ['True', 'False'],
        correctAnswer: 0,
        explanation: 'True. SQL = Structured Query Language.',
      },
      {
        id: 'db-q3',
        type: 'multiple_choice',
        questionText: 'Which command is used to add new rows to a table?',
        options: ['UPDATE', 'INSERT INTO', 'ADD ROW', 'CREATE DATA'],
        correctAnswer: 1,
        explanation: '`INSERT INTO table_name (columns) VALUES (values)` inserts new records.',
      },
      {
        id: 'db-q4',
        type: 'true_false',
        questionText: 'True or False: The `DELETE` command removes table structure completely from disk.',
        options: ['True', 'False'],
        correctAnswer: 1,
        explanation: 'False. `DELETE` removes rows; `DROP TABLE` removes the table structure.',
      },
      {
        id: 'db-q5',
        type: 'multiple_choice',
        questionText: 'Which SQL keyword sorts query results in descending order?',
        options: ['ORDER ASC', 'DESC', 'DOWN', 'SORT HIGH'],
        correctAnswer: 1,
        explanation: 'Use `ORDER BY column DESC` for descending order.',
      },
    ],
  },
  {
    id: 'course-net-101',
    title: 'Computer Networking',
    slug: 'computer-networking',
    description: 'Explore network architecture, IP addressing, TCP/UDP protocols, OSI model layers, DNS, and HTTP/HTTPS fundamentals.',
    iconName: 'Network',
    category: 'Networking',
    level: 'Beginner',
    estimatedHours: '3 Hours',
    passingScorePercent: 70,
    lessons: [
      {
        id: 'net-les-1',
        courseId: 'course-net-101',
        title: 'IP Addressing & Subnets',
        order: 1,
        summary: 'Learn IPv4 format, MAC addresses, public vs private networks, and DNS resolution.',
        explanation: 'An IP address uniquely identifies devices connected to a network. DNS (Domain Name System) translates human-readable domain names (apexflow.com) into numerical IP addresses (e.g. 192.0.2.1).',
        keyPoints: [
          'IPv4 consists of 4 octets (e.g. 192.168.1.1).',
          'MAC addresses uniquely identify hardware Network Interface Cards (NICs).',
          'DNS acts as the phonebook of the internet.',
        ],
        practiceQuestion: {
          question: 'What system translates human domain names like apexflow.com into IP addresses?',
          options: ['DHCP', 'DNS', 'HTTP', 'FTP'],
          correctAnswer: 1,
          explanation: 'DNS (Domain Name System) resolves domain names to numerical IP addresses.',
        },
        xpReward: 20,
      },
      {
        id: 'net-les-2',
        courseId: 'course-net-101',
        title: 'TCP vs UDP Protocols',
        order: 2,
        summary: 'Compare reliable connection-oriented TCP vs high-speed connectionless UDP transport layer protocols.',
        explanation: 'TCP guarantees packet delivery via 3-way handshake, making it ideal for web browsing. UDP prioritizes speed without packet delivery guarantees, making it suitable for live video streaming.',
        keyPoints: [
          'TCP: Reliable, ordered delivery (Handshake: SYN, SYN-ACK, ACK).',
          'UDP: Fast, lightweight, unordered delivery.',
        ],
        practiceQuestion: {
          question: 'Which transport protocol guarantees reliable packet delivery?',
          options: ['UDP', 'IP', 'TCP', 'ICMP'],
          correctAnswer: 2,
          explanation: 'TCP (Transmission Control Protocol) guarantees reliable delivery.',
        },
        xpReward: 20,
      },
    ],
    questions: [
      {
        id: 'net-q1',
        type: 'multiple_choice',
        questionText: 'Which OSI layer does HTTP operate on?',
        options: ['Layer 1 (Physical)', 'Layer 3 (Network)', 'Layer 4 (Transport)', 'Layer 7 (Application)'],
        correctAnswer: 3,
        explanation: 'HTTP is an Application Layer (Layer 7) protocol.',
      },
      {
        id: 'net-q2',
        type: 'true_false',
        questionText: 'True or False: HTTPS encrypts data transmission using TLS/SSL security.',
        options: ['True', 'False'],
        correctAnswer: 0,
        explanation: 'True. HTTPS encrypts HTTP traffic via TLS/SSL.',
      },
      {
        id: 'net-q3',
        type: 'multiple_choice',
        questionText: 'Standard HTTP web traffic connects over which default port?',
        options: ['Port 21', 'Port 80', 'Port 443', 'Port 22'],
        correctAnswer: 1,
        explanation: 'HTTP defaults to Port 80; HTTPS defaults to Port 443.',
      },
      {
        id: 'net-q4',
        type: 'true_false',
        questionText: 'True or False: A MAC address changes every time you connect to a new Wi-Fi network.',
        options: ['True', 'False'],
        correctAnswer: 1,
        explanation: 'False. MAC addresses are burned into physical hardware NICs.',
      },
      {
        id: 'net-q5',
        type: 'multiple_choice',
        questionText: 'Which network device routes traffic between different subnets/networks?',
        options: ['Network Switch', 'Router', 'Repeater', 'Hub'],
        correctAnswer: 1,
        explanation: 'Routers forward data packets across separate IP networks.',
      },
    ],
  },
  {
    id: 'course-ml-101',
    title: 'Machine Learning Fundamentals',
    slug: 'machine-learning-fundamentals',
    description: 'Understand supervised vs unsupervised learning, dataset splitting, training models, and evaluation metrics.',
    iconName: 'Cpu',
    category: 'AI & Data Science',
    level: 'Intermediate',
    estimatedHours: '4 Hours',
    passingScorePercent: 70,
    lessons: [
      {
        id: 'ml-les-1',
        courseId: 'course-ml-101',
        title: 'Supervised vs Unsupervised Learning',
        order: 1,
        summary: 'Distinguish between labeled training data classification and unlabeled cluster discovery.',
        explanation: 'Machine learning enables computers to learn patterns from data without explicit rules. Supervised learning trains models on labeled pairs (input X -> target Y). Unsupervised learning finds hidden clusters in unlabeled datasets.',
        keyPoints: [
          'Supervised: Classification (cat/dog) and Regression (price prediction).',
          'Unsupervised: Clustering (K-Means, customer grouping).',
          'Training Set vs Test Set evaluation.',
        ],
        practiceQuestion: {
          question: 'Predicting house prices based on size and location is an example of what type of learning?',
          options: ['Unsupervised Learning', 'Supervised Learning (Regression)', 'Reinforcement Learning', 'Manual Programming'],
          correctAnswer: 1,
          explanation: 'Predicting continuous numerical target values with labeled historical data is Supervised Regression.',
        },
        xpReward: 20,
      },
      {
        id: 'ml-les-2',
        courseId: 'course-ml-101',
        title: 'Model Evaluation & Overfitting',
        order: 2,
        summary: 'Evaluate accuracy, precision, recall, and prevent overfitting on training data.',
        explanation: 'Overfitting occurs when a model memorizes noise in the training dataset but fails to generalize to unseen test data.',
        keyPoints: [
          'Overfitting: High training accuracy, low test accuracy.',
          'Underfitting: Model is too simple to capture patterns.',
          'Split data into Train (80%) and Test (20%) sets.',
        ],
        practiceQuestion: {
          question: 'What happens when a machine learning model overfits?',
          options: [
            'It performs perfectly on unseen test data',
            'It memorizes training data but performs poorly on new test data',
            'It trains too quickly',
            'It has 0 parameters',
          ],
          correctAnswer: 1,
          explanation: 'Overfitting means memorizing training noise and failing to generalize.',
        },
        xpReward: 20,
      },
    ],
    questions: [
      {
        id: 'ml-q1',
        type: 'multiple_choice',
        questionText: 'Which learning paradigm uses labeled input-output pairs?',
        options: ['Unsupervised Learning', 'Supervised Learning', 'Clustering', 'Dimensionality Reduction'],
        correctAnswer: 1,
        explanation: 'Supervised learning requires labeled ground-truth targets.',
      },
      {
        id: 'ml-q2',
        type: 'true_false',
        questionText: 'True or False: We should evaluate machine learning models on the exact same dataset used to train them.',
        options: ['True', 'False'],
        correctAnswer: 1,
        explanation: 'False. Models must be evaluated on an independent test dataset to verify generalization.',
      },
      {
        id: 'ml-q3',
        type: 'multiple_choice',
        questionText: 'What is the target outcome of a classification task?',
        options: ['A continuous numerical number', 'A discrete category/class label', 'An SQL table', 'An IP address'],
        correctAnswer: 1,
        explanation: 'Classification predicts categorical labels (e.g., Spam / Not Spam).',
      },
      {
        id: 'ml-q4',
        type: 'true_false',
        questionText: 'True or False: Neural networks are inspired by biological brain neurons.',
        options: ['True', 'False'],
        correctAnswer: 0,
        explanation: 'True. Artificial Neural Networks model connected artificial neuron layers.',
      },
      {
        id: 'ml-q5',
        type: 'multiple_choice',
        questionText: 'Which metric measures the percentage of total correct predictions made by a model?',
        options: ['Loss', 'Variance', 'Accuracy', 'Learning Rate'],
        correctAnswer: 2,
        explanation: 'Accuracy = Correct Predictions / Total Predictions.',
      },
    ],
  },
];

export const seedDatabase = async (req: Request, res: Response): Promise<void> => {
  try {
    // 1. Seed Master Admin
    const adminEmail = 'admin@apexflow.edu';
    let admin = await User.findOne({ email: adminEmail });
    if (!admin) {
      const hashedPassword = await bcrypt.hash('ApexFlow2026!', 10);
      admin = new User({
        name: 'Academy Control Tower',
        email: adminEmail,
        password: hashedPassword,
        role: 'admin',
        xp: 1000,
        level: 10,
        joinedDate: '2026-01-01',
        enrolledCourses: [],
        completedLessons: [],
        completedCourses: [],
      });
      await admin.save();
    }

    // 2. Seed 6 Pre-configured Courses
    for (const c of initialCourses) {
      await Course.findOneAndUpdate({ slug: c.slug }, c, { upsert: true, new: true });
    }

    res.status(200).json({
      message: 'MongoDB Atlas successfully seeded with Master Admin and 6 pre-configured courses!',
      coursesCount: initialCourses.length,
      adminEmail,
    });
  } catch (error) {
    console.error('Database Seed Error:', error);
    res.status(500).json({ error: 'Failed to seed database' });
  }
};
