import { Task, Project, User, Activity, AnalyticsMetrics } from './types';

export const mockUsers: User[] = [
  {
    id: 'usr-1',
    name: 'Elena Vance',
    email: 'elena@apexflow.io',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'Product Lead',
    status: 'online',
  },
  {
    id: 'usr-2',
    name: 'Alex Rivera',
    email: 'alex@apexflow.io',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'Senior Frontend Architect',
    status: 'online',
  },
  {
    id: 'usr-3',
    name: 'Marcus Chen',
    email: 'marcus@apexflow.io',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'Backend Staff Engineer',
    status: 'busy',
  },
  {
    id: 'usr-4',
    name: 'Sophia Taylor',
    email: 'sophia@apexflow.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'UI/UX Design Director',
    status: 'online',
  },
  {
    id: 'usr-5',
    name: 'David Kim',
    email: 'david@apexflow.io',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    role: 'DevOps Lead',
    status: 'offline',
  },
];

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Apex Core Platform v2',
    key: 'APEX',
    description: 'Next-generation micro-frontend architecture & real-time collaboration engine.',
    color: 'from-indigo-500 to-cyan-500',
    category: 'Engineering',
    memberCount: 8,
    taskCount: 24,
    completedTaskCount: 16,
    updatedAt: '2026-09-12T10:00:00Z',
  },
  {
    id: 'proj-2',
    name: 'Mobile App Ecosystem',
    key: 'MOB',
    description: 'iOS and Android app redesign featuring offline-first data sync.',
    color: 'from-purple-500 to-pink-500',
    category: 'Mobile',
    memberCount: 5,
    taskCount: 18,
    completedTaskCount: 9,
    updatedAt: '2026-09-11T16:30:00Z',
  },
  {
    id: 'proj-3',
    name: 'AI Intelligence & Predictive Analytics',
    key: 'AI',
    description: 'Automated sprint forecasting, bottleneck detection & AI copilot.',
    color: 'from-emerald-500 to-teal-500',
    category: 'Data Science',
    memberCount: 4,
    taskCount: 14,
    completedTaskCount: 7,
    updatedAt: '2026-09-10T14:15:00Z',
  },
  {
    id: 'proj-4',
    name: 'Enterprise Security & SOC2 Compliance',
    key: 'SEC',
    description: 'Zero-trust architecture, audit logging, and automated vulnerability scanning.',
    color: 'from-amber-500 to-rose-500',
    category: 'Infrastructure',
    memberCount: 6,
    taskCount: 12,
    completedTaskCount: 10,
    updatedAt: '2026-09-09T09:20:00Z',
  },
];

export const mockTasks: Task[] = [
  {
    id: 'tsk-101',
    code: 'APEX-101',
    title: 'Architect GraphQL Subscriptions & WebSocket Gateway',
    description: 'Implement low-latency bi-directional WebSocket connections for live workspace updates across multi-region clusters.',
    status: 'in_progress',
    priority: 'urgent',
    assignee: mockUsers[2], // Marcus Chen
    tags: ['Architecture', 'WebSockets', 'Backend'],
    dueDate: '2026-09-16',
    projectId: 'proj-1',
    createdAt: '2026-09-08',
    estimatedHours: 24,
    timeLoggedHours: 16,
    subtasks: [
      { id: 'st-1', title: 'Setup Redis Pub/Sub cluster adapter', completed: true },
      { id: 'st-2', title: 'Implement client reconnect backoff handling', completed: true },
      { id: 'st-3', title: 'Add load balancer sticky session rules', completed: false },
    ],
    comments: [
      {
        id: 'cm-1',
        userId: 'usr-1',
        userName: 'Elena Vance',
        userAvatar: mockUsers[0].avatar,
        content: 'Crucial for sprint demo on Thursday. Make sure token authentication handshake handles key rotation.',
        createdAt: '2026-09-11T11:20:00Z',
      },
    ],
  },
  {
    id: 'tsk-102',
    code: 'APEX-102',
    title: 'Redesign Executive Analytics Dashboard Widgets',
    description: 'Create interactive charts for team throughput, burnup velocity, and milestone breakdown using CSS Grid & Glassmorphism.',
    status: 'in_review',
    priority: 'high',
    assignee: mockUsers[1], // Alex Rivera
    tags: ['Frontend', 'UI/UX', 'Design System'],
    dueDate: '2026-09-15',
    projectId: 'proj-1',
    createdAt: '2026-09-07',
    estimatedHours: 16,
    timeLoggedHours: 14,
    subtasks: [
      { id: 'st-4', title: 'Design high-contrast dark theme chart tooltips', completed: true },
      { id: 'st-5', title: 'Add animated count-up state for metric cards', completed: true },
      { id: 'st-6', title: 'Audit screen reader keyboard accessibility', completed: true },
    ],
    comments: [
      {
        id: 'cm-2',
        userId: 'usr-4',
        userName: 'Sophia Taylor',
        userAvatar: mockUsers[3].avatar,
        content: 'The glassmorphic blur effect looks top notch! Tested across 4K displays.',
        createdAt: '2026-09-12T08:45:00Z',
      },
    ],
  },
  {
    id: 'tsk-103',
    code: 'APEX-103',
    title: 'Implement Dark Glassmorphic Design Token Palette',
    description: 'Establish standard CSS custom variables for glass surfaces, glowing borders, radial mesh gradients, and active focus rings.',
    status: 'done',
    priority: 'high',
    assignee: mockUsers[3], // Sophia Taylor
    tags: ['Design System', 'Tailwind', 'CSS'],
    dueDate: '2026-09-10',
    projectId: 'proj-1',
    createdAt: '2026-09-02',
    estimatedHours: 12,
    timeLoggedHours: 12,
    subtasks: [
      { id: 'st-7', title: 'Export Figma token library to CSS custom properties', completed: true },
      { id: 'st-8', title: 'Create backdrop-blur component wrappers', completed: true },
    ],
    comments: [],
  },
  {
    id: 'tsk-104',
    code: 'APEX-104',
    title: 'Build Global Command Palette (⌘K) Search Modal',
    description: 'Keyboard-first fuzzy search shortcut to jump between projects, tasks, team members, and actions.',
    status: 'in_progress',
    priority: 'medium',
    assignee: mockUsers[1], // Alex Rivera
    tags: ['Frontend', 'Accessibility', 'Navigation'],
    dueDate: '2026-09-18',
    projectId: 'proj-1',
    createdAt: '2026-09-09',
    estimatedHours: 18,
    timeLoggedHours: 8,
    subtasks: [
      { id: 'st-9', title: 'Implement Cmd+K global keydown listener', completed: true },
      { id: 'st-10', title: 'Add recent searches local cache', completed: false },
      { id: 'st-11', title: 'Filter search results by section headers', completed: true },
    ],
    comments: [],
  },
  {
    id: 'tsk-105',
    code: 'APEX-105',
    title: 'Optimize Zero-Downtime CI/CD Kubernetes Pipeline',
    description: 'Automate blue-green deployment strategies with instant rollback capabilities on health check failure.',
    status: 'todo',
    priority: 'medium',
    assignee: mockUsers[4], // David Kim
    tags: ['DevOps', 'Kubernetes', 'CI/CD'],
    dueDate: '2026-09-20',
    projectId: 'proj-4',
    createdAt: '2026-09-10',
    estimatedHours: 20,
    timeLoggedHours: 4,
    subtasks: [
      { id: 'st-12', title: 'Configure ArgoCD deployment triggers', completed: false },
      { id: 'st-13', title: 'Test automated rollback scripts in staging', completed: false },
    ],
    comments: [],
  },
  {
    id: 'tsk-106',
    code: 'APEX-106',
    title: 'AI Sprint Capacity & Bottleneck Forecasting Model',
    description: 'Train machine learning model to estimate project completion likelihood based on historical team velocity and scope changes.',
    status: 'todo',
    priority: 'high',
    assignee: mockUsers[0], // Elena Vance
    tags: ['AI/ML', 'Analytics', 'Feature'],
    dueDate: '2026-09-22',
    projectId: 'proj-3',
    createdAt: '2026-09-11',
    estimatedHours: 32,
    timeLoggedHours: 6,
    subtasks: [
      { id: 'st-14', title: 'Build dataset pipeline from past 10 sprints', completed: true },
      { id: 'st-15', title: 'Create confidence interval visualizer component', completed: false },
    ],
    comments: [],
  },
  {
    id: 'tsk-107',
    code: 'APEX-107',
    title: 'Mobile Touch Gestures & Smooth Kanban Dragging',
    description: 'Refine touch response and drag target thresholds for tablet & mobile browsers.',
    status: 'backlog',
    priority: 'low',
    assignee: mockUsers[3], // Sophia Taylor
    tags: ['Mobile', 'UX', 'Touch'],
    dueDate: '2026-09-25',
    projectId: 'proj-2',
    createdAt: '2026-09-12',
    estimatedHours: 14,
    timeLoggedHours: 0,
    subtasks: [],
    comments: [],
  },
  {
    id: 'tsk-108',
    code: 'APEX-108',
    title: 'SOC2 Type II Audit Log Storage & Encryption',
    description: 'Encrypt audit event streams using AES-256 before persisting to immutable cloud buckets.',
    status: 'done',
    priority: 'urgent',
    assignee: mockUsers[4], // David Kim
    tags: ['Security', 'Compliance', 'Audit'],
    dueDate: '2026-09-08',
    projectId: 'proj-4',
    createdAt: '2026-09-01',
    estimatedHours: 16,
    timeLoggedHours: 16,
    subtasks: [
      { id: 'st-16', title: 'Configure KMS key rotation policy', completed: true },
      { id: 'st-17', title: 'Pass security compliance validation suite', completed: true },
    ],
    comments: [],
  },
];

export const mockActivities: Activity[] = [
  {
    id: 'act-1',
    userId: 'usr-2',
    userName: 'Alex Rivera',
    userAvatar: mockUsers[1].avatar,
    action: 'moved task',
    target: 'APEX-102 to In Review',
    timestamp: '12 mins ago',
  },
  {
    id: 'act-2',
    userId: 'usr-3',
    userName: 'Marcus Chen',
    userAvatar: mockUsers[2].avatar,
    action: 'logged 4.5 hours on',
    target: 'APEX-101 GraphQL Gateway',
    timestamp: '42 mins ago',
  },
  {
    id: 'act-3',
    userId: 'usr-4',
    userName: 'Sophia Taylor',
    userAvatar: mockUsers[3].avatar,
    action: 'commented on',
    target: 'APEX-102 Dashboard Widgets',
    timestamp: '2 hours ago',
  },
  {
    id: 'act-4',
    userId: 'usr-5',
    userName: 'David Kim',
    userAvatar: mockUsers[4].avatar,
    action: 'completed task',
    target: 'APEX-108 Audit Log Encryption',
    timestamp: '5 hours ago',
  },
];

export const mockAnalytics: AnalyticsMetrics = {
  totalTasks: 68,
  completedTasks: 42,
  inProgressTasks: 18,
  urgentTasks: 4,
  completionRate: 61.7,
  sprintVelocity: 94.2,
  hoursSpent: 312,
};
